Dev
LLC-Polipak/PyOdata1C pull request #1
Opened 2024-08-22 15:19 UTC by through-your-tears

2024-08-23 07:56 UTC, kr-aleksey requested changes
В целом хоро. Есть некоторые замечания по текущему коду. Соблюдай PEP8 (длина строки). Рекомендую использовать flake8 и flake8-isort. Текущая реализация не позволяет менять приоритет объединения скобками, например (p1 == 0 | p2 =='foo') & p3 > 100. Над этим нужно будет еще поработать.

2024-08-23 08:29 UTC, thecodest22 reviewed
В целом выглядит норм, давай шпарь дальше. 

Пожелания:
1) Как быть, если надо явно указать приоритет операторов с помощью скобок? Сейчас скобки игногируются.

2) Нередко приходится делать фильтрацию, например, по нескольким Ref_Key.
В текущей реализации это можно сделать, вызывая на каждый рефкей конструкцию типа ```(my_field == value) | (my_field == value1) ...```
И это будет многа букаф.

Шеф предложил отличную идею:
Можно передавать в качестве значения коллекцию данных типа списка. А под капотом конкатенировать результат примерно так:
```' or '.join(f"{self.source} eq '{item}'" for item in sequence)```

3) Проверь условные конструкции. У тебя много где ненужные "else", хотя можно просто "return"

2024-08-23 11:01 UTC, through-your-tears commented on PyOdata1C/fields.py
> +    def __init__(self, source: str, cast: bool = False, cast_on: str | None = None):
Docstringи есть в планах, сделаю их чуть позже

2024-09-03 06:24 UTC, thecodest22 commented on PyOdata1C/fields.py
> +        return self._build_result_field(value, 'eq')
Строки 152-168 - везде 'eq' в аргументах _build_result_field

2024-09-03 06:24 UTC, thecodest22 commented on PyOdata1C/view.py
> +            query_params['$filter'] = self.__select_params
Возможно, "self.__filter_params"?

2024-09-03 06:24 UTC, thecodest22 commented on PyOdata1C/view.py
> +        return self
В этих методах не забудь проверку на всякое гуано, вроде запятой в конце select ))

2024-09-03 07:18 UTC, kr-aleksey requested changes
Есть замечание. Pull request доводи до логического завершения. Иправляй или обсуждай замечания, чтобы я мог смерджить код. В целом для прогесса за неделю маловато, ускоряйся.

2024-09-12 10:23 UTC, kr-aleksey requested changes
Есть замечания

2024-09-12 10:23 UTC, kr-aleksey commented on PyOdata1C/view.py
> +    config: Config = None
Аннотируем Config, присваиваем None

2024-09-12 11:27 UTC, through-your-tears commented on PyOdata1C/fields.py
> +    def __eq__(self, other: str | float | datetime) -> FilterResultField:
> Разве у нас other не объект класса Field или FilterResultField?

Нет, т.к. это сравнение с любым объектом, который может быть превращён в datetime, который будет представлен уже в формате, подходящем для 1С(ну или том, который передан в конструктор класса)

2024-09-12 15:25 UTC, through-your-tears commented on PyOdata1C/validators.py
> +    def compare(cls, a, b):
> Лучше избегать одно буквенных переменных.

В данном случае очевидно, что метод compare с переменными на вход a и b будет сравнивать эти a и b

2024-09-12 18:09 UTC, through-your-tears commented on PyOdata1C/validators.py
> +        if message:
> А с пустой строкой работать будет?

Если пустая строка будет string pattern, то да, будет, всегда работать
Если message будет пустая строка, то сообщение будет такое же, как и до этого

2024-09-13 06:51 UTC, kr-aleksey commented on PyOdata1C/fields.py
> +    def __init__(self, source: str, cast: bool = False, cast_on: str | None = None):
Они нужны уже сейчас, для проведения ревью

2024-09-16 12:38 UTC, closed without merging